### ISSUE TITLE
#feature: add support for bounded calls

### ISSUE THREAD

**Issue by bananabr** [ambionics/mt_rand-reverse#1]
I am not sure if that would be even possible, but it is fairly common to encounter applications using the bounded version of mt_rand. Would the attack still apply?

**Comment by bananabr** [comment]
As the modulus operation is not reversible I think you would have to check every possible candidate that could generate the value for n+0 and n+227 right? Even for 32-bits this is a lot for small bound values =T

PS.: Simplifying the problem and ignoring corner cases.

**Comment by cfreal** [comment]
Hello,

I missed this, sorry.

Yes, as you said, it's pretty hard to pull it off using bounded calls.
For instance, when generating a password, you get like mt_rand(26*2+10), which is 62, meaning you have 2**32/62 candidates for n+0 and n+227. This is way too many.

You can probably implement an attack that takes (n+0 n+1 n+2 ...) and (n+227 n+228 n+229 ...) and intersect the sets but I guess you might as well bruteforce the seed...

So, it might be doable; is it useful ? Probably not, sadly.
Please keep me posted about your research if you try to pull this off !

Charles
